---
- name: restart and enable mongodb
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: mongod
  
- name: restart and enable todoapp
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: todoapp
